server:
  port: 8083

spring:
  datasource:
    username: sa
    url: jdbc:h2:file:./data/demo


keycloak:
  server:
    contextPath: /auth
    adminUser:
      username: aamir
      password: deadman
    realmImportFile: dips-realm.json
  