server:
  port: $PORT

spring:
  datasource:
    username: sa
    url: jdbc:h2:mem:testdb


keycloak:
  server:
    contextPath: /auth
    adminUser:
      username: aamir
      password: deadman
    realmImportFile: dips-realm.json
  